<a href="https://colab.research.google.com/github/phdsx/Pytorch-NLP/blob/main/%E9%BB%91%E9%A9%AC%E7%A8%8B%E5%BA%8F%E5%91%98NLP%EF%BC%88P1~6%EF%BC%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# P1

导入

In [21]:
import torch,numpy

空矩阵

In [4]:
x=torch.empty(5,3)
print(x)

tensor([[-2.7445e-13,  3.0767e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


随机矩阵

In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.7961, 0.4973, 0.1876],
        [0.7048, 0.7478, 0.4999],
        [0.8302, 0.3618, 0.5026],
        [0.5292, 0.7454, 0.2834],
        [0.2832, 0.4187, 0.8654]])


In [8]:
x=torch.zeros(5,3,dtype=torch.long)
y=torch.zeros(5,3,dtype=torch.double)
print(x,y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [9]:
x=torch.rand(5,3)
print(x)

tensor([[0.2619, 0.4961, 0.3552],
        [0.4741, 0.9441, 0.0703],
        [0.0604, 0.5770, 0.0337],
        [0.4685, 0.6185, 0.2921],
        [0.7657, 0.9099, 0.3920]])


In [13]:
print(x[1,:])

tensor([0.4741, 0.9441, 0.0703])


In [14]:
y=x.view(15)
print(y)

tensor([0.2619, 0.4961, 0.3552, 0.4741, 0.9441, 0.0703, 0.0604, 0.5770, 0.0337,
        0.4685, 0.6185, 0.2921, 0.7657, 0.9099, 0.3920])


In [15]:
y=x.view(-1,5)
print(y)

tensor([[0.2619, 0.4961, 0.3552, 0.4741, 0.9441],
        [0.0703, 0.0604, 0.5770, 0.0337, 0.4685],
        [0.6185, 0.2921, 0.7657, 0.9099, 0.3920]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [20]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-2.4638])
-2.4638311862945557


In [22]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(3)
print(a,b)

tensor([4., 4., 4., 4., 4.]) [4. 4. 4. 4. 4.]


# P6 类型转换2

In [27]:
a=numpy.ones(5)
b=torch.from_numpy(a)
numpy.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')